In [1]:
import yaml
import json
import pandas as pd

with open("../../config/config.yaml", "r") as f:
    config = yaml.safe_load(f)
    
MIN_OVERVIEW_WORDS = config["data_preprocessing"]["min_overview_words"] #6
MAX_OVERVIEW_WORDS = config["data_preprocessing"]["max_overview_words"] #169

tmdb_df = pd.read_csv("../../data/raw/TMDB_movie_dataset_v11.csv", usecols=['title', 'vote_average', 'vote_count', 'popularity', 'release_date', 'status', 'runtime', 'adult', "overview", 'genres', 'production_companies', 'production_countries', 'keywords'])
print(f"TMDB shape: {tmdb_df.shape}")
tmdb_df.head()

TMDB shape: (1367573, 13)

,title,vote_average,vote_count,status,release_date,runtime,adult,overview,popularity,genres,production_companies,production_countries,keywords
0,Inception,8.364,34495,Released,2010-07-15,148,False,"Cobb, a skilled thief who commits corporate es...",83.952,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","rescue, mission, dream, airplane, paris, franc..."
1,Interstellar,8.417,32571,Released,2014-11-05,169,False,The adventures of a group of explorers who mak...,140.241,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America","rescue, future, spacecraft, race against time,..."
2,The Dark Knight,8.512,30619,Released,2008-07-16,152,False,Batman raises the stakes in his war on crime. ...,130.643,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","joker, sadism, chaos, secret identity, crime f..."
3,Avatar,7.573,29815,Released,2009-12-15,162,False,"In the 22nd century, a paraplegic Marine is di...",79.932,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","future, society, culture clash, space travel, ..."
4,The Avengers,7.710,29166,Released,2012-04-25,143,False,When an unexpected enemy emerges and threatens...,98.082,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"new york city, superhero, shield, based on com..."

In [2]:
import pandas as pd
import json

letterbox = []
for line in open("../../data/raw/full_dump.jsonl", "r"):
    letterbox.append(json.loads(line))

letterbox_df = pd.DataFrame(letterbox)
letterbox_df.drop(['url', 'reviews', 'poster_url', 'rating'], axis=1, inplace=True)
letterbox_df.drop_duplicates(subset=['title'], inplace=True, ignore_index=True)
letterbox_df

,title,year,directors,genres,cast,synopsis
0,Come and See,1985,[Elem Klimov],"[War, Drama]","[Aleksei Kravchenko, Olga Mironova, Liubomiras...",The invasion of a village in Byelorussia by Ge...
1,Seven Samurai,1954,[Akira Kurosawa],"[Action, Drama]","[Toshirō Mifune, Takashi Shimura, Yoshio Inaba...",A samurai answers a village's request for prot...
2,High and Low,1963,[Akira Kurosawa],"[Mystery, Thriller, Crime, Drama]","[Toshirō Mifune, Tatsuya Nakadai, Kyōko Kagawa...",In the midst of an attempt to take over his co...
3,Harakiri,1962,[Masaki Kobayashi],"[History, Drama, Action]","[Tatsuya Nakadai, Akira Ishihama, Shima Iwashi...",Down-on-his-luck veteran Tsugumo Hanshirō ente...
4,12 Angry Men,1957,[Sidney Lumet],[Drama],"[Martin Balsam, John Fiedler, Lee J. Cobb, E.G...",The defense and the prosecution have rested an...
...,...,...,...,...,...,...
694511,Road Wars: Max Fury,2024,[Mark Atkins],"[Science Fiction, Adventure, Action]","[Chandni Shah, Preet Kaur, Lindsey Marie Wilso...","In a post-apocalyptic wasteland, two sisters l..."
694512,El Fil Fel Mandil,2011,[Ahmed ElBadry],[Comedy],"[Talaat Zakaria, Nana, Mohamed El Sobky, Ramy ...",An unassuming fruit seller is assigned a cruci...
694513,Wonderwell,2023,[Vlad Marsavin],"[Family, Fantasy, Drama]","[Kiera Milward, Nell Tiger Free, Carrie Fisher...","In an idyllic Italian village, a young America..."
694514,The Changeover,2017,"[Stuart McKenzie, Miranda Harcourt]","[Fantasy, Horror, Thriller]","[Timothy Spall, Melanie Lynskey, Lucy Lawless,...","Laura Chant, 16, lives with her mother and fou..."
694515,Leprechaun: The Beginning,2025,[Rahul Gandhi],[Horror],"[Amanda Jane York, Mark Collier, Julia Quayle,...",A family discovers a treasure box of gold in t...

In [3]:
# Нормализация названий для матчинга
def normalize_title(title):
    if pd.isna(title):
        return ""
    title = str(title).lower().strip()
    title = title.replace("the ", "").replace("a ", "").replace("an ", "")
    title = ''.join(c for c in title if c.isalnum() or c.isspace())
    return ' '.join(title.split())

tmdb = tmdb_df.copy()
letterbox = letterbox_df.copy()

tmdb['title_norm'] = tmdb['title'].apply(normalize_title)
letterbox['title_norm'] = letterbox['title'].apply(normalize_title)

tmdb['year'] = pd.to_datetime(tmdb['release_date'], errors='coerce').dt.year.astype('Int64')
letterbox['year'] = letterbox['year'].astype('Int64')

# Full outer join на normalized title и year
merged = pd.merge(
    tmdb,
    letterbox,
    how='outer',
    on=['title_norm', 'year'],
    suffixes=('_tmdb', '_lb')
)

# Удаляем дубликаты по title_norm (если нужно, добавь year в subset)
merged = merged.drop_duplicates(subset=['title_norm'], keep='first')

# Убираем временную колонку
merged = merged.drop(columns=['title_norm'], errors='ignore')
merged.reset_index(drop=True, inplace=True)
# Сохраняем
merged.to_csv('../../data/raw/union_tmdb_letterboxd.csv', index=False)

print(f"Merged shape: {merged.shape}")
merged = merged[["title_tmdb", "title_lb", "status", "release_date", "year", "vote_average", "vote_count", "popularity", "runtime", "adult", "overview", "synopsis", "genres_tmdb", "genres_lb", "directors", "cast", "production_countries", "production_companies", "keywords"]]
print(f"Merged shape: {merged.shape}")

print(merged.info())
merged

Merged shape: (1168081, 19)
Merged shape: (1168081, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1168081 entries, 0 to 1168080
Data columns (total 19 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   title_tmdb            1075443 non-null  object
 1   title_lb              635226 non-null   object
 2   status                1075443 non-null  object
 3   release_date          888534 non-null   object
 4   year                  975784 non-null   Int64
 5   vote_average          1075443 non-null  float64
 6   vote_count            1075443 non-null  float64
 7   popularity            1075443 non-null  float64
 8   runtime               1075443 non-null  float64
 9   adult                 1075443 non-null  object
 10  overview              818172 non-null   object
 11  synopsis              535340 non-null   object
 12  genres_tmdb           612946 non-null   object
 13  genres_lb             476472 non-null   object
 14  directors             538304 non-null   object
 15  cast                  440576 non-null   object
 16  production_countries  576348 non-null   object
 17  production_companies  479020 non-null   object
 18  keywords              272542 non-null   object
dtypes: Int64(1), float64(4), object(14)
memory usage: 170.4+ MB
None

,title_tmdb,title_lb,status,release_date,year,vote_average,vote_count,popularity,runtime,adult,overview,synopsis,genres_tmdb,genres_lb,directors,cast,production_countries,production_companies,keywords
0,,NaN,Released,1921-09-01,1921,0.0,0.0,0.6000,6.0,False,A look at an exhibition in Reval (now known as...,NaN,Documentary,NaN,NaN,NaN,Soviet Union,NaN,NaN
1,0,NaN,Released,1977-01-01,1977,0.0,0.0,0.6000,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,France,NaN,NaN
2,0 & 1,0 & 1,Released,2002-02-14,2002,0.0,0.0,1.4000,74.0,False,"A girl called Zero stands in a crowded street,...","A girl called Zero stands in a crowded street,...","Drama, Crime","[Drama, Crime]",[Kei Nakata],"[Eri Ishikawa, Takayuki Katô, Joe Yamanaka, Is...",Japan,NaN,NaN
3,0 and 26,0 and 26,Released,2016-12-23,2016,8.5,2.0,0.6000,43.0,False,The Tampa Bay Buccaneers losing their first ev...,The Tampa Bay Buccaneers losing their first ev...,Documentary,[Documentary],NaN,"[Ron Wolf, Steve Spurrier, J.K. McKay, Rich Mc...",NaN,NFL Films,NaN
4,0% Down,0% Down,Released,2008-01-01,2008,0.0,0.0,0.6000,6.0,False,Meckseper's parodic high-octane video 0% Down ...,Meckseper's parodic high-octane video 0% Down ...,NaN,NaN,[Josephine Meckseper],NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1168076,𝒀𝑬𝑳𝑳𝑶𝑾,NaN,Released,NaN,<NA>,0.0,0.0,0.6000,10.0,False,When an alleged business meeting turns into an...,NaN,"Drama, Thriller",NaN,NaN,NaN,NaN,One Way Mirror,NaN
1168077,{𝕮𝖆𝖑𝖑 𝖀𝖘} How do I talk to someone through BLO...,NaN,Released,NaN,<NA>,0.0,0.0,0.0000,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1168078,𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮,𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮,Released,2023-11-21,2023,0.0,0.0,0.0000,36.0,False,"The film is about inspiration, reminding the p...","The film is about inspiration, reminding the p...",Documentary,[Documentary],[Regie Mae Adelantar],"[Lou Veloso, Boyet Magale, Sylvia Lichauco De ...",Philippines,The Archivist,"philippines, manila philippines, cultural iden..."
1168079,𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵,NaN,Released,2025-09-07,2025,0.0,0.0,0.0357,0.0,False,Sadie Finloch disappeared in 1973. What happened?,NaN,NaN,NaN,NaN,NaN,United Kingdom,NaN,NaN
1168080,𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚,NaN,Post Production,NaN,<NA>,0.0,0.0,0.0071,30.0,False,"In Taiwan’s struggles for housing justice, it ...",NaN,Documentary,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#working with title
merged['title'] = merged['title_tmdb'].combine_first(merged['title_lb'])
merged.drop(columns=['title_tmdb', 'title_lb'], inplace=True)

In [7]:
#working with release_date
print(merged['status'].value_counts())
merged.drop(merged[merged['status'].isin(["Canceled", "Rumored", "Planned"])].index, inplace=True)
print(merged['status'].value_counts())

merged['release_info'] = (
    merged['release_date']
    .combine_first(merged['year'])
    .combine_first(merged['status'])
)
merged.drop(columns=['release_date', 'year', 'status'], inplace=True)

status
Released           1045665
In Production        13880
Post Production       8472
Planned               6743
Rumored                452
Canceled               231
Name: count, dtype: int64
status
Released           1045665
In Production        13880
Post Production       8472
Name: count, dtype: int64

In [8]:
merged["overview_new"] = merged["overview"].combine_first(merged["synopsis"])
merged.drop(columns=['overview', 'synopsis'], inplace=True)

In [9]:
merged["genres"] = merged['genres_tmdb'].combine_first(merged['genres_lb'])
merged.drop(columns=['genres_tmdb', 'genres_lb'], inplace=True)

In [10]:
#TODO убрать все ненужные данные (adult true) подумать про runtime 0, release неясный 
#TODO и затем попробовать объединить рейтинг
merged = merged[['title', 'release_info', 'overview_new', 'vote_average', 'vote_count', 'popularity', 'runtime', 'genres', 'adult','directors', 'cast', 'production_countries', 'production_companies', 'keywords']]
merged.rename(columns={'overview_new':'overview'}, inplace=True)
merged.reset_index(drop=True, inplace=True)
print(merged.info())
merged

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1160655 entries, 0 to 1160654
Data columns (total 14 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   title                 1160655 non-null  object
 1   release_info          1155267 non-null  object
 2   overview              905847 non-null   object
 3   vote_average          1068017 non-null  float64
 4   vote_count            1068017 non-null  float64
 5   popularity            1068017 non-null  float64
 6   runtime               1068017 non-null  float64
 7   genres                700595 non-null   object
 8   adult                 1068017 non-null  object
 9   directors             536533 non-null   object
 10  cast                  439421 non-null   object
 11  production_countries  571588 non-null   object
 12  production_companies  474419 non-null   object
 13  keywords              270570 non-null   object
dtypes: float64(4), object(10)
memory usage: 124.0+ MB
None

,title,release_info,overview,vote_average,vote_count,popularity,runtime,genres,adult,directors,cast,production_countries,production_companies,keywords
0,,1921-09-01,A look at an exhibition in Reval (now known as...,0.0,0.0,0.6000,6.0,Documentary,False,NaN,NaN,Soviet Union,NaN,NaN
1,0,1977-01-01,NaN,0.0,0.0,0.6000,0.0,NaN,False,NaN,NaN,France,NaN,NaN
2,0 & 1,2002-02-14,"A girl called Zero stands in a crowded street,...",0.0,0.0,1.4000,74.0,"Drama, Crime",False,[Kei Nakata],"[Eri Ishikawa, Takayuki Katô, Joe Yamanaka, Is...",Japan,NaN,NaN
3,0 and 26,2016-12-23,The Tampa Bay Buccaneers losing their first ev...,8.5,2.0,0.6000,43.0,Documentary,False,NaN,"[Ron Wolf, Steve Spurrier, J.K. McKay, Rich Mc...",NaN,NFL Films,NaN
4,0% Down,2008-01-01,Meckseper's parodic high-octane video 0% Down ...,0.0,0.0,0.6000,6.0,NaN,False,[Josephine Meckseper],NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160650,𝒀𝑬𝑳𝑳𝑶𝑾,Released,When an alleged business meeting turns into an...,0.0,0.0,0.6000,10.0,"Drama, Thriller",False,NaN,NaN,NaN,One Way Mirror,NaN
1160651,{𝕮𝖆𝖑𝖑 𝖀𝖘} How do I talk to someone through BLO...,Released,NaN,0.0,0.0,0.0000,0.0,NaN,False,NaN,NaN,NaN,NaN,NaN
1160652,𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮,2023-11-21,"The film is about inspiration, reminding the p...",0.0,0.0,0.0000,36.0,Documentary,False,[Regie Mae Adelantar],"[Lou Veloso, Boyet Magale, Sylvia Lichauco De ...",Philippines,The Archivist,"philippines, manila philippines, cultural iden..."
1160653,𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵,2025-09-07,Sadie Finloch disappeared in 1973. What happened?,0.0,0.0,0.0357,0.0,NaN,False,NaN,NaN,United Kingdom,NaN,NaN
1160654,𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚,Post Production,"In Taiwan’s struggles for housing justice, it ...",0.0,0.0,0.0071,30.0,Documentary,False,NaN,NaN,NaN,NaN,NaN

In [11]:
merged.drop(merged[merged['title'].isin([" ", ""])].index, inplace=True)

In [10]:
merged.dropna(subset=['overview'], inplace=True, ignore_index=True)
merged['overview_length'] = merged['overview'].apply(lambda x: len(x.split()))
merged.drop(merged[merged['overview_length'] < MIN_OVERVIEW_WORDS].index, inplace=True)
merged.reset_index(drop=True, inplace=True)

In [11]:
merged.drop(merged[merged['adult'] == True].index, inplace=True)
merged.drop('adult', axis=1, inplace=True)
merged.reset_index(drop=True, inplace=True)
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773275 entries, 0 to 773274
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   title                 773275 non-null  object
 1   release_info          770320 non-null  object
 2   overview              773275 non-null  object
 3   vote_average          699017 non-null  float64
 4   vote_count            699017 non-null  float64
 5   popularity            699017 non-null  float64
 6   runtime               699017 non-null  float64
 7   genres                553050 non-null  object
 8   directors             452885 non-null  object
 9   cast                  373772 non-null  object
 10  production_countries  398653 non-null  object
 11  production_companies  310750 non-null  object
 12  keywords              192738 non-null  object
 13  overview_length       773275 non-null  int64
dtypes: float64(4), int64(1), object(9)
memory usage: 82.6+ MB

In [12]:
merged['overview_length'].describe()

count    773275.000000
mean         47.202890
std          34.568713
min           6.000000
25%          21.000000
50%          37.000000
75%          65.000000
max         237.000000
Name: overview_length, dtype: float64

In [13]:
def truncate_overview(text: str) -> str:
    
    words = text.split()
    if len(words) > MAX_OVERVIEW_WORDS:
        return " ".join(words[:MAX_OVERVIEW_WORDS]) + '...'
    return text

merged['overview'] = merged['overview'].apply(truncate_overview)

In [14]:
merged['overview_length'] = merged['overview'].apply(lambda x: len(x.split()))
merged['overview_length'].describe()

count    773275.000000
mean         47.187261
std          34.510755
min           6.000000
25%          21.000000
50%          37.000000
75%          65.000000
max         169.000000
Name: overview_length, dtype: float64

In [15]:
merged.drop('overview_length', axis=1, inplace=True)
merged.info()
merged

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773275 entries, 0 to 773274
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   title                 773275 non-null  object
 1   release_info          770320 non-null  object
 2   overview              773275 non-null  object
 3   vote_average          699017 non-null  float64
 4   vote_count            699017 non-null  float64
 5   popularity            699017 non-null  float64
 6   runtime               699017 non-null  float64
 7   genres                553050 non-null  object
 8   directors             452885 non-null  object
 9   cast                  373772 non-null  object
 10  production_countries  398653 non-null  object
 11  production_companies  310750 non-null  object
 12  keywords              192738 non-null  object
dtypes: float64(4), object(9)
memory usage: 76.7+ MB

,title,release_info,overview,vote_average,vote_count,popularity,runtime,genres,directors,cast,production_countries,production_companies,keywords
0,0 & 1,2002-02-14,"A girl called Zero stands in a crowded street,...",0.0,0.0,1.4000,74.0,"Drama, Crime",[Kei Nakata],"[Eri Ishikawa, Takayuki Katô, Joe Yamanaka, Is...",Japan,NaN,NaN
1,0 and 26,2016-12-23,The Tampa Bay Buccaneers losing their first ev...,8.5,2.0,0.6000,43.0,Documentary,NaN,"[Ron Wolf, Steve Spurrier, J.K. McKay, Rich Mc...",NaN,NFL Films,NaN
2,0% Down,2008-01-01,Meckseper's parodic high-octane video 0% Down ...,0.0,0.0,0.6000,6.0,NaN,[Josephine Meckseper],NaN,NaN,NaN,NaN
3,0 Feet Away,2014-12-15,"Looking for a good time, Chase stays home one ...",0.0,0.0,0.6000,10.0,NaN,NaN,NaN,NaN,NaN,NaN
4,0 Lux,Released,A man clearing out his recently deceased fathe...,0.0,0.0,0.0000,7.0,Horror,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
773270,𝐓𝐡𝐞 𝐕𝐢𝐠𝐢𝐥𝐚𝐧𝐭 𝐕𝐢𝐥𝐥𝐚𝐠𝐞𝐫𝐬,Released,This is the story of three Filipino rural comm...,0.0,0.0,0.0000,42.0,NaN,NaN,NaN,NaN,NaN,NaN
773271,𝒀𝑬𝑳𝑳𝑶𝑾,Released,When an alleged business meeting turns into an...,0.0,0.0,0.6000,10.0,"Drama, Thriller",NaN,NaN,NaN,One Way Mirror,NaN
773272,𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮,2023-11-21,"The film is about inspiration, reminding the p...",0.0,0.0,0.0000,36.0,Documentary,[Regie Mae Adelantar],"[Lou Veloso, Boyet Magale, Sylvia Lichauco De ...",Philippines,The Archivist,"philippines, manila philippines, cultural iden..."
773273,𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵,2025-09-07,Sadie Finloch disappeared in 1973. What happened?,0.0,0.0,0.0357,0.0,NaN,NaN,NaN,United Kingdom,NaN,NaN
773274,𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚,Post Production,"In Taiwan’s struggles for housing justice, it ...",0.0,0.0,0.0071,30.0,Documentary,NaN,NaN,NaN,NaN,NaN

In [16]:
def genres_to_list(genres:list | str | float):
    if type(genres) == str:
        genres = genres.split(", ")
    
    return genres

merged['genres'] = merged['genres'].apply(genres_to_list)

In [17]:
merged

,title,release_info,overview,vote_average,vote_count,popularity,runtime,genres,directors,cast,production_countries,production_companies,keywords
0,0 & 1,2002-02-14,"A girl called Zero stands in a crowded street,...",0.0,0.0,1.4000,74.0,"[Drama, Crime]",[Kei Nakata],"[Eri Ishikawa, Takayuki Katô, Joe Yamanaka, Is...",Japan,NaN,NaN
1,0 and 26,2016-12-23,The Tampa Bay Buccaneers losing their first ev...,8.5,2.0,0.6000,43.0,[Documentary],NaN,"[Ron Wolf, Steve Spurrier, J.K. McKay, Rich Mc...",NaN,NFL Films,NaN
2,0% Down,2008-01-01,Meckseper's parodic high-octane video 0% Down ...,0.0,0.0,0.6000,6.0,NaN,[Josephine Meckseper],NaN,NaN,NaN,NaN
3,0 Feet Away,2014-12-15,"Looking for a good time, Chase stays home one ...",0.0,0.0,0.6000,10.0,NaN,NaN,NaN,NaN,NaN,NaN
4,0 Lux,Released,A man clearing out his recently deceased fathe...,0.0,0.0,0.0000,7.0,[Horror],NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
773270,𝐓𝐡𝐞 𝐕𝐢𝐠𝐢𝐥𝐚𝐧𝐭 𝐕𝐢𝐥𝐥𝐚𝐠𝐞𝐫𝐬,Released,This is the story of three Filipino rural comm...,0.0,0.0,0.0000,42.0,NaN,NaN,NaN,NaN,NaN,NaN
773271,𝒀𝑬𝑳𝑳𝑶𝑾,Released,When an alleged business meeting turns into an...,0.0,0.0,0.6000,10.0,"[Drama, Thriller]",NaN,NaN,NaN,One Way Mirror,NaN
773272,𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮,2023-11-21,"The film is about inspiration, reminding the p...",0.0,0.0,0.0000,36.0,[Documentary],[Regie Mae Adelantar],"[Lou Veloso, Boyet Magale, Sylvia Lichauco De ...",Philippines,The Archivist,"philippines, manila philippines, cultural iden..."
773273,𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵,2025-09-07,Sadie Finloch disappeared in 1973. What happened?,0.0,0.0,0.0357,0.0,NaN,NaN,NaN,United Kingdom,NaN,NaN
773274,𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚,Post Production,"In Taiwan’s struggles for housing justice, it ...",0.0,0.0,0.0071,30.0,[Documentary],NaN,NaN,NaN,NaN,NaN

In [18]:
merged["title_plot"] = merged.apply(lambda row: f"Title: {row["title"]} Plot: {row["overview"]}", axis=1)

In [ ]:
def process_meta_info(row):
    meta_parts = []
    
    #Release info
    release_info = row['release_info']
    if pd.isna(release_info):
        meta_parts.append("Release: Unknown")
    elif release_info in ["Released", "In Production", "Post Production"]:
        meta_parts.append(f"{release_info}")
    else:
        meta_parts.append(f"Released in {release_info}")
    
    #Rating, votes, popularity, runtime
    if pd.isna(row['vote_average']):
        meta_parts.append("Rating: Unknown")
    else:
        meta_parts.append(f"Rating: {row['vote_average']:.1f}/10")
    
    if pd.isna(row['vote_count']):
        meta_parts.append("Votes: Unknown")
    else:
        meta_parts.append(f"{row['vote_count']:.0f} votes")
    
    if pd.isna(row['popularity']):
        meta_parts.append("Popularity: Unknown")
    else:
        meta_parts.append(f"Popularity: {row['popularity']:.1f}")
    
    if pd.isna(row['runtime']) or row['runtime'] == 0:
        meta_parts.append("Runtime: Unknown")
    else:
        meta_parts.append(f"Runtime: {row['runtime']:.0f} min")
    
    #Genres
    genres = row["genres"]
    if type(genres) == float or not genres:
        meta_parts.append("Genres: Unknown")
    else:
        meta_parts.append(f"Genres: {", ".join(genres)}")
        
    #Directors
    directors = row['directors']
    if type(directors) == float or not directors:
        meta_parts.append("Directors: Unknown")
    else:
        meta_parts.append(f"Directors: {", ".join(directors)}")
    
    #Cast
    cast = row['cast']
    if type(cast) == float or not cast:
        meta_parts.append("Cast: Unknown")
    else:
        top_cast = ', '.join(cast[:5])
        meta_parts.append(f"Cast: {top_cast}")
    
    #Production countries
    if pd.isna(row["production_countries"]):
        meta_parts.append("Production countries: Unknown")
    else:
        meta_parts.append(f"Production countries: {row["production_countries"]}")
    
    #Production companies
    if pd.isna(row["production_companies"]):
        meta_parts.append("Production companies: Unknown")
    else:
        meta_parts.append(f"Production companies: {row["production_companies"]}")
    
    #Keywords
    if type(row['keywords']) != float:
        keywords = row['keywords'].split(", ")
        if len(keywords) >= 3:
            kw_str = ', '.join([k for k in keywords[:10]])
            meta_parts.append(f"Tags: {kw_str}")
    
    return " | ".join(meta_parts)

merged['title_meta'] = merged.apply(process_meta_info, axis=1)

In [26]:
print(merged['title_plot'].iloc[0])
print(merged['title_meta'].iloc[0])

Title: 0 & 1 Plot: A girl called Zero stands in a crowded street, her occupation an assassin. As she completes her tasks one after another, Zero has been feeling uneasy lately. As her code name suggests, she has nothing to prove her existence. She overlaps herself with the vanishing landscape and begins to wander in search of the meaning of her own existence. At the same time, a young man named One is also wandering the streets, and like Zero, he is an assassin. Surrounded by a sense of emptiness, he is unable to find the value of his own existence. One day, the two of them meet as if they were led together. They sense each other, and by touching each other, they regain their existence and humanity. However, the organization feels that contact between assassins is dangerous, and decides to dispose of them. They call in a highly skilled assassin. Their battle for their own existence begins now!
Released in 2002-02-14 | Rating: 0.0/10 | 0 votes | Popularity: 1.4 | Runtime: 74 min | Genres: Drama, Crime | Directors Kei Nakata | Cast: Eri Ishikawa, Takayuki Katô, Joe Yamanaka, Isao Natsuyagi, Natsuyo Kanahama | Production countries: Japan | Production countries: Unknown

In [ ]:
# def process_meta_info(row):
#     if row['release_info'] in ["Released", "In Production", "Post Production"]:
#         release = row["release_info"]
#     else:
#         release = f"Released in {row["release_info"]}"
    
#     rating = f"Rating: {row["vote_average"]:.1f}/10"
#     votes = f"{row["vote_count"]:.0f} votes"
#     popularity = f"Popularity: {row["popularity"]:.1f}"
#     runtime = f"Runtime: {row['runtime']:.0f} min"
    
#     print(rating)
#     print(votes)
#     print(popularity)
#     print(runtime)

# genres_types = set()
# for genre in merged['production_companies']:
#     genres_types.add(type(genre))
# print(genres_types)

# directors_types = set()
# for director in merged['production_countries']:
#     directors_types.add(type(director))
# print(directors_types)

# cast_types = set()
# for cast in merged['keywords']:
#     cast_types.add(type(cast))
# print(cast_types)

{<class 'float'>, <class 'str'>}
{<class 'str'>, <class 'float'>}
{<class 'float'>, <class 'str'>}

In [1]:
import pandas as pd
import numpy as np
import pickle


with open("../../indexes/faiss_metadata.pkl", "rb") as f:
    metadata = pickle.load(f)

In [2]:
for idx in metadata[:10]:
    print(idx)

{'row_idx': 0, 'chunk_type': 'meta', 'title': '0 & 1', 'chunk_text': '0 & 1 | Released in 2002-02-14 | Rating: 0.0/10 | 0 votes | Popularity: 1.4 | Runtime: 74 min | Genres: Drama, Crime | Directors: Kei Nakata | Cast: Eri Ishikawa, Takayuki Katô, Joe Yamanaka, Isao Natsuyagi, Natsuyo Kanahama | Production countries: Japan | Production companies: Unknown'}
{'row_idx': 0, 'chunk_type': 'plot', 'title': '0 & 1', 'chunk_text': 'Title: 0 & 1 Plot: A girl called Zero stands in a crowded street, her occupation an assassin. As she completes her tasks one after another, Zero has been feeling uneasy lately. As her code name suggests, she has nothing to prove her existence. She overlaps herself with the vanishing landscape and begins to wander in search of the meaning of her own existence. At the same time, a young man named One is also wandering the streets, and like Zero, he is an assassin. Surrounded by a sense of emptiness, he is unable to find the value of his own existence. One day, the two of them meet as if they were led together. They sense each other, and by touching each other, they regain their existence and humanity. However, the organization feels that contact between assassins is dangerous, and decides to dispose of them. They call in a highly skilled assassin. Their battle for their own existence begins now!'}
{'row_idx': 1, 'chunk_type': 'meta', 'title': '0 and 26', 'chunk_text': '0 and 26 | Released in 2016-12-23 | Rating: 8.5/10 | 2 votes | Popularity: 0.6 | Runtime: 43 min | Genres: Documentary | Directors: Unknown | Cast: Ron Wolf, Steve Spurrier, J.K. McKay, Rich McKay, Pat Toomay | Production countries: Unknown | Production companies: NFL Films'}
{'row_idx': 1, 'chunk_type': 'plot', 'title': '0 and 26', 'chunk_text': 'Title: 0 and 26 Plot: The Tampa Bay Buccaneers losing their first ever 26 games.'}
{'row_idx': 2, 'chunk_type': 'meta', 'title': '0% Down', 'chunk_text': '0% Down | Released in 2008-01-01 | Rating: 0.0/10 | 0 votes | Popularity: 0.6 | Runtime: 6 min | Genres: Unknown | Directors: Josephine Meckseper | Cast: Unknown | Production countries: Unknown | Production companies: Unknown'}
{'row_idx': 2, 'chunk_type': 'plot', 'title': '0% Down', 'chunk_text': 'Title: 0% Down Plot: Meckseper\'s parodic high-octane video 0% Down (2008) engages the politics of consumerism that undeniably extend to the automotive industry. Meckseper edited the most militaristic and aggressive sequences of campaigns produced by various manufacturers—including Ford, Saab, Mazda, Toyota, Mercedes, and Chevrolet—into a six-minute, black-and-white montage. Boyd Rice’s industrial noise anthem “Total War" accompanies the imagery. As a male voice shouts, “Do you want? Yes you want…Total War!” seemingly indestructible cars are glorified in implausible scenarios. A military aircraft morphs into an SUV, a truck drives through swinging metal beams in a rock quarry, and a sedan plays chicken with a fighter jet. While similar types of commercials run daily on American television sets, when grouped together in 0% Down, they appear absurd. - UTexas'}
{'row_idx': 3, 'chunk_type': 'meta', 'title': '0 Feet Away', 'chunk_text': '0 Feet Away | Released in 2014-12-15 | Rating: 0.0/10 | 0 votes | Popularity: 0.6 | Runtime: 10 min | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production countries: Unknown | Production companies: Unknown'}
{'row_idx': 3, 'chunk_type': 'plot', 'title': '0 Feet Away', 'chunk_text': "Title: 0 Feet Away Plot: Looking for a good time, Chase stays home one night searching for a hook-up, using one of the many apps on his phone. What starts off as a flirty conversation with Stealth, ends up getting creepier, until there's not much more than zero feet between them."}
{'row_idx': 4, 'chunk_type': 'meta', 'title': '0 Lux', 'chunk_text': '0 Lux | Released | Rating: 0.0/10 | 0 votes | Popularity: 0.0 | Runtime: 7 min | Genres: Horror | Directors: Unknown | Cast: Unknown | Production countries: Unknown | Production companies: Unknown'}
{'row_idx': 4, 'chunk_type': 'plot', 'title': '0 Lux', 'chunk_text': "Title: 0 Lux Plot: A man clearing out his recently deceased father's house discovers a camcorder that offers a bittersweet glimpse of his father for the last time."}

In [6]:
import pandas as pd

df = pd.read_csv("../../data/prep/film_data.csv")

In [21]:
filmes = df[df["title"].isin(["Snatch", 
                              "Kingsman: The Secret Service", 
                              "The Hateful Eight", 
                              "Lock, Stock and Two Smoking Barrels", 
                              "Interstellar",
                              "Wrath of Man",
                              "Once Upon a Time... in Hollywood",
                              "Cars 2",
                              ])]
filmes

,Unnamed: 0,title,release_info,overview,vote_average,vote_count,popularity,runtime,genres,directors,cast,production_countries,production_companies,keywords,title_plot,title_meta
112067,112067,Cars 2,2011-06-11,Star race car Lightning McQueen and his pal Ma...,6.080,7115.0,72.036,106.0,"['Animation', 'Family', 'Adventure', 'Comedy']",['John Lasseter'],"['Larry the Cable Guy', 'Owen Wilson', 'Michae...",United States of America,"Pixar, Walt Disney Pictures","car race, sequel, anthropomorphism, best frien...",Title: Cars 2 Plot: Star race car Lightning Mc...,Cars 2 | Released in 2011-06-11 | Rating: 6.1/...
284360,284360,The Hateful Eight,2015-12-25,Bounty hunters seek shelter from a raging bliz...,7.746,13291.0,32.119,188.0,"['Drama', 'Mystery', 'Western']",['Quentin Tarantino'],"['Samuel L. Jackson', 'Kurt Russell', 'Jennife...",United States of America,"The Weinstein Company, Double Feature Films, F...","bounty hunter, wyoming, usa, narration, mounta...",Title: The Hateful Eight Plot: Bounty hunters ...,The Hateful Eight | Released in 2015-12-25 | R...
331181,331181,Interstellar,2014-11-05,The adventures of a group of explorers who mak...,8.417,32571.0,140.241,169.0,"['Adventure', 'Drama', 'Science Fiction']",['Christopher Nolan'],"['Matthew McConaughey', 'Anne Hathaway', 'Mich...","United Kingdom, United States of America","Legendary Pictures, Syncopy, Lynda Obst Produc...","rescue, future, spacecraft, race against time,...",Title: Interstellar Plot: The adventures of a ...,Interstellar | Released in 2014-11-05 | Rating...
364580,364580,Kingsman: The Secret Service,2014-12-13,The story of a super-secret spy organization t...,7.636,15664.0,56.288,129.0,"['Crime', 'Comedy', 'Action', 'Adventure']",NaN,NaN,"United Kingdom, United States of America","20th Century Fox, Marv Films, Cloudy Productio...","great britain, spy, secret organization, secre...",Title: Kingsman: The Secret Service Plot: The ...,Kingsman: The Secret Service | Released in 201...
402896,402896,"Lock, Stock and Two Smoking Barrels",1998-08-28,A card shark and his unwillingly-enlisted frie...,8.126,6072.0,10.500,105.0,"['Comedy', 'Crime']",['Guy Ritchie'],"['Vinnie Jones', 'Jason Flemyng', 'Dexter Flet...","United Kingdom, United States of America","Summit Entertainment, The Steve Tisch Company,...","ambush, joint, alcohol, shotgun, tea, machismo...","Title: Lock, Stock and Two Smoking Barrels Plo...","Lock, Stock and Two Smoking Barrels | Released..."
628501,628501,Snatch,2000-09-01,"Unscrupulous boxing promoters, violent bookmak...",7.801,8309.0,36.730,103.0,"['Crime', 'Comedy']",['Guy Ritchie'],"['Jason Statham', 'Alan Ford', 'Stephen Graham...","United Kingdom, United States of America","SKA Films, Columbia Pictures, Screen Gems","robbery, trailer park, england, gypsy, gamblin...",Title: Snatch Plot: Unscrupulous boxing promot...,Snatch | Released in 2000-09-01 | Rating: 7.8/...
759902,759902,Wrath of Man,2021-04-22,A cold and mysterious new security guard for a...,7.669,4632.0,56.933,119.0,"['Crime', 'Thriller', 'Action']",['Guy Ritchie'],"['Jason Statham', 'Holt McCallany', 'Rocci Wil...","United Kingdom, United States of America","Miramax, Metro-Goldwyn-Mayer, Toff Guy Films, ...","robbery, crime boss, revenge, shootout, shoote...",Title: Wrath of Man Plot: A cold and mysteriou...,Wrath of Man | Released in 2021-04-22 | Rating...

In [22]:
filmes_desc = filmes[["title", "overview"]]
for _, row in  filmes_desc.iterrows():
    print(f"{row["title"]}: {row["overview"]}")

Cars 2: Star race car Lightning McQueen and his pal Mater head overseas to compete in the World Grand Prix race. But the road to the championship becomes rocky as Mater gets caught up in an intriguing adventure of his own: international espionage.
The Hateful Eight: Bounty hunters seek shelter from a raging blizzard and get caught up in a plot of betrayal and deception.
Interstellar: The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.
Kingsman: The Secret Service: The story of a super-secret spy organization that recruits an unrefined but promising street kid into the agency's ultra-competitive training program just as a global threat emerges from a twisted tech genius.
Lock, Stock and Two Smoking Barrels: A card shark and his unwillingly-enlisted friends need to make a lot of cash quick after losing a sketchy poker match. To do this they decide to pull a heist on a small-time gang who happen to be operating out of the flat next door.
Snatch: Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.
Wrath of Man: A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.

In [15]:
genres = set()

def get_unique_genres(genre_str):
    if type(genre_str) == str:
        genre = genre_str[2:-2]
        if "', '" in genre:
            genres_ = genre.split("', '")
            for genre in genres_:
                genres.add(genre)
        else:
            genres.add(genre)
        
    return genre_str

In [17]:
df["genres"].apply(get_unique_genres)

0         ['Drama', 'Crime']
1            ['Documentary']
2                        NaN
3                        NaN
4                 ['Horror']
                 ...
781871       ['Documentary']
781872                   NaN
781873       ['Documentary']
781874                   NaN
781875                   NaN
Name: genres, Length: 781876, dtype: object

In [18]:
print(genres)

{'Quirky and endearing relationships', 'Drama', 'Horror', 'Show All…', 'Challenging or sexual themes & twists', 'Faith and spiritual journeys', 'Racism and the powerful fight for justice', 'Graphic violence and brutal revenge', 'Erotic relationships and desire', 'Crude humor and satire', 'Family', 'Horror, the undead and monster classics', 'Touching and sentimental family stories', 'Comedy', 'Action comedy and silly heroics\', "Kids\' animated fun and adventure", \'Gags, jokes, and slapstick humor', 'Historical battles and epic heroism', 'Dangerous technology and the apocalypse', 'Documentary', 'Western', 'Tragic sadness and captivating beauty', 'Relationship comedy', 'War', 'Intense violence and sexual transgression', 'Laugh-out-loud relationship entanglements', 'Emotional LGBTQ relationships', 'Survival horror and zombie carnage', 'Terrifying, haunted, and supernatural horror', 'Adventure', 'Crime', 'Animation', 'Dreamlike, quirky, and surreal storytelling', 'Powerful stories of heartbreak and suffering', 'Fairy-tale fantasy and enchanted magic', 'Fantasy adventure, heroism, and swordplay', 'Imaginative space odysseys and alien encounters', 'Thriller', 'Thought-provoking sci-fi action and future technology', 'Superheroes in action-packed battles with villains', 'Captivating relationships and charming romance', 'Music', 'Monsters, aliens, sci-fi and the apocalypse', 'Bollywood emotional dramas', 'Humanity and the world around us', 'Action-packed space and alien sagas', 'Gripping, intense violent crime', 'Epic adventure and breathtaking battles', 'Extreme gory horror and cannibalism', 'Fascinating, emotional stories and documentaries', 'History', 'Amusing jokes and witty satire', 'Catchy songs and hilarious musical comedy', 'Emotional and touching family dramas', 'Epic history and literature', 'Moving relationship stories', 'Twisted dark psychological thriller', 'Romance', 'Explosive and action-packed heroes vs. villains', 'Faith and religion', 'Religious faith, sin, and forgiveness', 'Captivating vision and Shakespearean drama', 'Underdogs and coming of age', 'Student coming-of-age challenges', 'Science Fiction', 'Charming romances and delightful chemistry', 'Epic heroes', 'Action', 'Crime, drugs and gangsters', 'Mystery', 'Fantasy', 'Gory, gruesome, and slasher horror', 'TV Movie'}

In [1]:
import pandas as pd

df = pd.read_csv("../../data/prep/film_data.csv")
df.shape

(1003142, 16)

In [2]:
df.head()

,Unnamed: 0,title,release_info,overview,vote_average,vote_count,popularity,runtime,genres,directors,cast,production_countries,production_companies,keywords,title_plot,title_meta
0,0,0 and 26,2016-12-23,The Tampa Bay Buccaneers losing their first ev...,8.5,2.0,0.6,43.0,['Documentary'],NaN,"['Ron Wolf', 'Steve Spurrier', 'J.K. McKay', '...",NaN,NFL Films,NaN,0 and 26 | Plot: The Tampa Bay Buccaneers losi...,0 and 26 | Released in 2016-12-23 | Genres: Do...
1,1,0% Down,2008-01-01,Meckseper's parodic high-octane video 0% Down ...,0.0,0.0,0.6,6.0,NaN,['Josephine Meckseper'],NaN,NaN,NaN,NaN,0% Down | Plot: Meckseper's parodic high-octan...,0% Down | Released in 2008-01-01 | Genres: Unk...
2,2,0 Feet Away,2014-12-15,"Looking for a good time, Chase stays home one ...",0.0,0.0,0.6,10.0,NaN,NaN,NaN,NaN,NaN,NaN,"0 Feet Away | Plot: Looking for a good time, C...",0 Feet Away | Released in 2014-12-15 | Genres:...
3,3,0 Lux,Released,A man clearing out his recently deceased fathe...,0.0,0.0,0.0,7.0,['Horror'],NaN,NaN,NaN,NaN,NaN,0 Lux | Plot: A man clearing out his recently ...,0 Lux | Released | Genres: Horror | Directors:...
4,4,#0. sisocisP,1992-01-01,"""[An] experiment that aims to highlight the nu...",0.0,0.0,0.6,3.0,NaN,['Antoni Pinent'],NaN,Spain,NaN,NaN,"#0. sisocisP | Plot: ""[An] experiment that aim...",#0. sisocisP | Released in 1992-01-01 | Genres...

In [2]:
df.dropna(subset=["title"], inplace=True)
print(f"after removing nans: {df.shape}")

def clear_title(title: str):
    return title if any(c.isalpha() for c in title) else ""

df_cleared = df.copy()
df_cleared["title"] = df_cleared["title"].apply(clear_title)

after removing nans: (1018689, 16)

In [3]:
df_cleared["title"].value_counts()

title
                                             2492
Home                                          190
Untitled                                      158
Mother                                        134
Alone                                         119
                                             ...
Guilt Trip: Hitchcock and 'The Wrong Man'       1
Guiltea                                         1
Guilt-Edged Blonde                              1
Guilt-Free Pleasures                            1
Guilt Is Not Mine                               1
Name: count, Length: 826184, dtype: int64

In [4]:
df_cleared.head()
df_cleared.drop(df_cleared[df_cleared["title"].isin([" ", ""])].index, inplace=True)

In [5]:
df_cleared.shape

(1016197, 16)

In [6]:
df_cleared.drop_duplicates(inplace=True)
df_cleared.shape

(1016197, 16)

In [7]:
df_cleared

,Unnamed: 0,title,release_info,overview,vote_average,vote_count,popularity,runtime,genres,directors,cast,production_countries,production_companies,keywords,title_plot,title_meta
569,569,0 and 26,2016-12-23,The Tampa Bay Buccaneers losing their first ev...,8.5,2.0,0.6000,43.0,['Documentary'],NaN,"['Ron Wolf', 'Steve Spurrier', 'J.K. McKay', '...",NaN,NFL Films,NaN,0 and 26 | Plot: The Tampa Bay Buccaneers losi...,0 and 26 | Released in 2016-12-23 | Genres: Do...
570,570,0% Down,2008-01-01,Meckseper's parodic high-octane video 0% Down ...,0.0,0.0,0.6000,6.0,NaN,['Josephine Meckseper'],NaN,NaN,NaN,NaN,0% Down | Plot: Meckseper's parodic high-octan...,0% Down | Released in 2008-01-01 | Genres: Unk...
571,571,0 Feet Away,2014-12-15,"Looking for a good time, Chase stays home one ...",0.0,0.0,0.6000,10.0,NaN,NaN,NaN,NaN,NaN,NaN,"0 Feet Away | Plot: Looking for a good time, C...",0 Feet Away | Released in 2014-12-15 | Genres:...
572,572,0 Lux,Released,A man clearing out his recently deceased fathe...,0.0,0.0,0.0000,7.0,['Horror'],NaN,NaN,NaN,NaN,NaN,0 Lux | Plot: A man clearing out his recently ...,0 Lux | Released | Genres: Horror | Directors:...
573,573,#0. sisocisP,1992-01-01,"""[An] experiment that aims to highlight the nu...",0.0,0.0,0.6000,3.0,NaN,['Antoni Pinent'],NaN,Spain,NaN,NaN,"#0. sisocisP | Plot: ""[An] experiment that aim...",#0. sisocisP | Released in 1992-01-01 | Genres...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1018686,1018686,𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮,2023-11-21,"The film is about inspiration, reminding the p...",0.0,0.0,0.0000,36.0,['Documentary'],['Regie Mae Adelantar'],"['Lou Veloso', 'Boyet Magale', 'Sylvia Lichauc...",Philippines,The Archivist,"philippines, manila philippines, cultural iden...",𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮 | Plot: The film...,𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮 | Released in 20...
1018687,1018687,𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵,2025-09-07,Sadie Finloch disappeared in 1973. What happened?,0.0,0.0,0.0357,0.0,NaN,NaN,NaN,United Kingdom,NaN,NaN,𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵 | Plot: Sad...,𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵 | Released ...
1018688,1018688,𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚,Post Production,"In Taiwan’s struggles for housing justice, it ...",0.0,0.0,0.0071,30.0,['Documentary'],NaN,NaN,NaN,NaN,NaN,𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚 | Plot: In Taiwan’s st...,𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚 | Post Production | Ge...
1018689,1018689,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕[[Does Coinbase do instant ...,Released,Coinbase supports💢【𝟷Σ𝟾𝟾𝟾☞𝟼𝟹𝟺☞𝟸𝟹𝟾𝟷〉 instant wit...,0.0,0.0,0.0286,0.0,NaN,NaN,NaN,NaN,NaN,NaN,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕[[Does Coinbase do instant ...,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕[[Does Coinbase do instant ...
1018690,1018690,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕⌊How to [⍟reverse] a 𝕮𝖔𝖎𝖓𝖇𝖆...,Released,Reversing a {☃️+𝟷✔️(𝟾𝟾𝟾)⋗(𝟼𝟹𝟺)⁂[𝟸𝟹𝟾𝟷]Coinbase ...,0.0,0.0,0.0214,0.0,NaN,NaN,NaN,NaN,NaN,NaN,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕⌊How to [⍟reverse] a 𝕮𝖔𝖎𝖓𝖇𝖆...,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕⌊How to [⍟reverse] a 𝕮𝖔𝖎𝖓𝖇𝖆...

In [ ]:
import numpy as np
cols = ["vote_average", "vote_count", "popularity", "runtime", "genres", "directors", "cast", "production_companies", "production_countries", "keywords"]

mask = (df_cleared[cols].isin([0]) | df_cleared[cols].isna()).all(axis=1)

df_bez = df_cleared[~mask]

In [13]:
df_bez

,Unnamed: 0,title,release_info,overview,vote_average,vote_count,popularity,runtime,genres,directors,cast,production_countries,production_companies,keywords,title_plot,title_meta
821,821,1 855 510 5815 Delta Airlines Boarding Pass,Released,A Delta Airlines 1+855+510+5815 boarding pass...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1 855 510 5815 Delta Airlines Boarding Pass | ...,1 855 510 5815 Delta Airlines Boarding Pass | ...
822,822,〔+1〉- 855- 510- 5815 ~ United Airlines Boardi...,Released,A United Airlines boarding pass is an essentia...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,〔+1〉- 855- 510- 5815 ~ United Airlines Boardi...,〔+1〉- 855- 510- 5815 ~ United Airlines Boardi...
828,828,+1➟ ((888))➟844➟((3638)) How much does geek sq...,Released,How Much Does Geek Squad Cost to Fix a PC? Cal...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,+1➟ ((888))➟844➟((3638)) How much does geek sq...,+1➟ ((888))➟844➟((3638)) How much does geek sq...
892,892,"1 kertas, 2 nasib",Released,"Because of a piece of paper, two people have d...",0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"1 kertas, 2 nasib | Plot: Because of a piece o...","1 kertas, 2 nasib | Released | Genres: Unknown..."
933,933,1 of 1: Genesis,2014,A film exploring the notion that superstar ath...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 of 1: Genesis | Plot: A film exploring the n...,1 of 1: Genesis | Released in 2014 | Genres: U...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1018661,1018661,（⊙ｏ⊙）™↶ Can't sign into earthlink webmail?,Released,{{866}}{{396}}{{8330}} If you can’t sign into ...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,（⊙ｏ⊙）™↶ Can't sign into earthlink webmail? | P...,（⊙ｏ⊙）™↶ Can't sign into earthlink webmail? | R...
1018666,1018666,(^._.^)ﾉHow to cancel geek squad,Released,"To cancel Geek Squad, simply call their toll-f...",0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,(^._.^)ﾉHow to cancel geek squad | Plot: To ca...,(^._.^)ﾉHow to cancel geek squad | Released | ...
1018672,1018672,⋆.𐙚 ̊ How do I cancel my Best Buy total yearly...,Released,To cancel your Best Buy Total yearly membershi...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,⋆.𐙚 ̊ How do I cancel my Best Buy total yearly...,⋆.𐙚 ̊ How do I cancel my Best Buy total yearly...
1018676,1018676,𓆩♛𓆪 How do I renew my Best Buy Geek Squad prot...,Released,"To renew your Best Buy Geek Squad protection, ...",0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,𓆩♛𓆪 How do I renew my Best Buy Geek Squad prot...,𓆩♛𓆪 How do I renew my Best Buy Geek Squad prot...
1018682,1018682,𝐌𝐘 𝐀𝐑𝐓𝐢 𝐅𝐈𝐋𝐌 | KARINA,Released,KARINA challenges herself to a noir action fil...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,𝐌𝐘 𝐀𝐑𝐓𝐢 𝐅𝐈𝐋𝐌 | KARINA | Plot: KARINA challenge...,𝐌𝐘 𝐀𝐑𝐓𝐢 𝐅𝐈𝐋𝐌 | KARINA | Released | Genres: Unk...

In [6]:
import pickle

with open('../../indexes/faiss_metadata.pkl', 'rb') as f:
    data = pickle.load(f)
    
print(data)

[{'row_idx': 0, 'chunk_type': 'meta', 'title': '0 and 26', 'chunk_text': '0 and 26 | Released in 2016-12-23 | Genres: Documentary | Directors: Unknown | Cast: Ron Wolf, Steve Spurrier, J.K. McKay, Rich McKay, Pat Toomay, Dewey Selmon, Mark Cotney | Production companies: NFL Films'}, {'row_idx': 0, 'chunk_type': 'plot', 'title': '0 and 26', 'chunk_text': '0 and 26 | Plot: The Tampa Bay Buccaneers losing their first ever 26 games.'}, {'row_idx': 1, 'chunk_type': 'meta', 'title': '0% Down', 'chunk_text': '0% Down | Released in 2008-01-01 | Genres: Unknown | Directors: Josephine Meckseper | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 1, 'chunk_type': 'plot', 'title': '0% Down', 'chunk_text': '0% Down | Plot: Meckseper\'s parodic high-octane video 0% Down (2008) engages the politics of consumerism that undeniably extend to the automotive industry. Meckseper edited the most militaristic and aggressive sequences of campaigns produced by various manufacturers—including Ford, Saab, Mazda, Toyota, Mercedes, and Chevrolet—into a six-minute, black-and-white montage. Boyd Rice’s industrial noise anthem “Total War" accompanies the imagery. As a male voice shouts, “Do you want? Yes you want…Total War!” seemingly indestructible cars are glorified in implausible scenarios. A military aircraft morphs into an SUV, a truck drives through swinging metal beams in a rock quarry, and a sedan plays chicken with a fighter jet. While similar types of commercials run daily on American television sets, when grouped together in 0% Down, they appear absurd. - UTexas'}, {'row_idx': 2, 'chunk_type': 'meta', 'title': '0 Feet Away', 'chunk_text': '0 Feet Away | Released in 2014-12-15 | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 2, 'chunk_type': 'plot', 'title': '0 Feet Away', 'chunk_text': "0 Feet Away | Plot: Looking for a good time, Chase stays home one night searching for a hook-up, using one of the many apps on his phone. What starts off as a flirty conversation with Stealth, ends up getting creepier, until there's not much more than zero feet between them."}, {'row_idx': 3, 'chunk_type': 'meta', 'title': '0 Lux', 'chunk_text': '0 Lux | Released | Genres: Horror | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 3, 'chunk_type': 'plot', 'title': '0 Lux', 'chunk_text': "0 Lux | Plot: A man clearing out his recently deceased father's house discovers a camcorder that offers a bittersweet glimpse of his father for the last time."}, {'row_idx': 4, 'chunk_type': 'meta', 'title': '#0. sisocisP', 'chunk_text': '#0. sisocisP | Released in 1992-01-01 | Genres: Unknown | Directors: Antoni Pinent | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 4, 'chunk_type': 'plot', 'title': '#0. sisocisP', 'chunk_text': '#0. sisocisP | Plot: "[An] experiment that aims to highlight the number of shots of a specific scene [from Hitchcock\'s Psycho] by replacing the shot of the image with several of the credit titles from the same film [...] An early work, which would be the first official of Pinent\'s filmography, made when he was only 16 years old, [...] Two years away from Matthias Müller\'s \'found footage\' reference work, \'Home Stories\' (1990), a key piece in the genre." -Center de Cultura Contemporània de Barcelona'}, {'row_idx': 5, 'chunk_type': 'meta', 'title': "0 to 60mph: Britain's Fastest Kids", 'chunk_text': "0 to 60mph: Britain's Fastest Kids | Released in 2016-11-20 | Genres: Documentary | Directors: Unknown | Cast: Unknown | Production companies: Unknown"}, {'row_idx': 5, 'chunk_type': 'plot', 'title': "0 to 60mph: Britain's Fastest Kids", 'chunk_text': "0 to 60mph: Britain's Fastest Kids | Plot: Unveiling Britain’s competitive karting scene and some of Britain’s most promising young drivers, working towards their ultimate goal of reaching Formula One."}, {'row_idx': 6, 'chunk_type': 'meta', 'title': '00 Schneider - Im Wendekreis der Eidechse', 'chunk_text': '00 Schneider - Im Wendekreis der Eidechse | Released in 2013-06-30 | Genres: Comedy | Directors: Helge Schneider | Cast: Helge Schneider, Rocko Schamoni, Sergej Gleithmann, Peter Thoms, Pete York, Tyree Glenn, Rudi Olbrich, Antoinette Clinton | Production companies: Senator Film'}, {'row_idx': 6, 'chunk_type': 'plot', 'title': '00 Schneider - Im Wendekreis der Eidechse', 'chunk_text': "00 Schneider - Im Wendekreis der Eidechse | Plot: A dangerous gangster called the Lizard escaped from prison. He steals chickens and spits on old ladies. There's only one man who can catch him: the commissioner Roy Schneider!"}, {'row_idx': 7, 'chunk_type': 'meta', 'title': '00 Schneider - Jagd auf Nihil Baxter', 'chunk_text': '00 Schneider - Jagd auf Nihil Baxter | Released in 1994-12-21 | Genres: Comedy, Crime | Directors: Christoph Schlingensief, Helge Schneider | Cast: Helge Schneider, Helmut Körschgen, Andreas Kunze, Otto Van den Berg, Guenther Kordas, Hotte Reichlich, Charlie Weiss, Tim Janssen, Eva Kurowski, Werner Abrolat | Production companies: Senator Film'}, {'row_idx': 7, 'chunk_type': 'plot', 'title': '00 Schneider - Jagd auf Nihil Baxter', 'chunk_text': '00 Schneider - Jagd auf Nihil Baxter | Plot: The funny clown Bratislav Metulskie is found dead in circus "Apollo". The retired commissioner 00 Schneider is asked to assume control of the case. Schneider and his aged sidekick Körschgen investigate to find the murderer.'}, {'row_idx': 8, 'chunk_type': 'meta', 'title': '00 Woman - Im Reich der Klofrau', 'chunk_text': '00 Woman - Im Reich der Klofrau | Released in 2003-01-01 | Genres: Comedy | Directors: Beatrice Manowski | Cast: Beatrice Manowski | Production companies: Unknown'}, {'row_idx': 8, 'chunk_type': 'plot', 'title': '00 Woman - Im Reich der Klofrau', 'chunk_text': '00 Woman - Im Reich der Klofrau | Plot: The adventures of a toilet cleaner.'}, {'row_idx': 9, 'chunk_type': 'meta', 'title': '0000 Kilometre', 'chunk_text': '0000 Kilometre | Released in 2024 | Genres: Drama, Romance | Directors: Deniz Enyüksek | Cast: Derya Pınar Ak, Ahmet Haktan Zavlak, Gülin İyigün, Ogün Kaptanoğlu, Cavit Çetin Güner, Can Kızıltuğ, Oya İloğulları, Laçin Ergül, Anıl Özgür, Meltem Akçöl | Production companies: Unknown'}, {'row_idx': 9, 'chunk_type': 'plot', 'title': '0000 Kilometre', 'chunk_text': "0000 Kilometre | Plot: A phone call to Izmir while she and Ege are living together in France turns their lives upside down. The caller claims to be Izmir's recently deceased mother."}, {'row_idx': 10, 'chunk_type': 'meta', 'title': '00:00 Meia-Noite', 'chunk_text': '00:00 Meia-Noite | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 10, 'chunk_type': 'plot', 'title': '00:00 Meia-Noite', 'chunk_text': '00:00 Meia-Noite | Plot: An essay on love, friendship, sex, identity and art, led by the gaze of a group of young people who struggle with reaching adulthood.'}, {'row_idx': 11, 'chunk_type': 'meta', 'title': '00:00 Midnight', 'chunk_text': '00:00 Midnight | Released in 2024 | Genres: Drama, Romance | Directors: Ana Luis Quintão, Filipa Pereira Pinto | Cast: Shanice Prentis, Marta Fatal, Will Costa, Eloy Gomes, Catarina Campos, Inês Meira | Production companies: Unknown'}, {'row_idx': 11, 'chunk_type': 'plot', 'title': '00:00 Midnight', 'chunk_text': '00:00 Midnight | Plot: An essay on love, friendship, sex, identity and art, led by the gaze of a group of young people who struggle with reaching adulthood.'}, {'row_idx': 12, 'chunk_type': 'meta', 'title': '0000: A Shark Odyssey', 'chunk_text': '0000: A Shark Odyssey | Released in 2020-09-16 | Genres: Animation, Comedy, Music, Science Fiction | Directors: Unknown | Cast: Unknown | Production companies: Ènèng Studios'}, {'row_idx': 12, 'chunk_type': 'plot', 'title': '0000: A Shark Odyssey', 'chunk_text': '0000: A Shark Odyssey | Plot: In the year 0000, the world is inhabited by sharks who speak the Sharkish language. But one day everything seems to be coming to an end. Unknown forces want to manipulate these sharks using anagrams.'}, {'row_idx': 13, 'chunk_type': 'meta', 'title': '00:00: Urban Strange Story', 'chunk_text': '00:00: Urban Strange Story | In Production | Genres: Thriller, Mystery | Directors: Khoa Nguyễn, Nguyễn Đức Nhật Thanh | Cast: Oanh Kiều, Lý Hồng Ân, Nhung Gumiho, Thư Nguyễn, Nguyễn Anh Tú, Bảo Trung | Production companies: nColors Production | Tags: urban life, stranger, chuyện kỳ dị'}, {'row_idx': 13, 'chunk_type': 'plot', 'title': '00:00: Urban Strange Story', 'chunk_text': '00:00: Urban Strange Story | Plot: The collection of urban strange stories'}, {'row_idx': 14, 'chunk_type': 'meta', 'title': '00007.mov', 'chunk_text': '00007.mov | Released in 2023-09-18 | Genres: Comedy | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 14, 'chunk_type': 'plot', 'title': '00007.mov', 'chunk_text': '00007.mov | Plot: A group of film students set up equipment to shoot a short film for a 72 hour film challenge.'}, {'row_idx': 15, 'chunk_type': 'meta', 'title': '0000E8', 'chunk_text': '0000E8 | Released in 2020-09-05 | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 15, 'chunk_type': 'plot', 'title': '0000E8', 'chunk_text': '0000E8 | Plot: What are you going to do when a giant blue star-like object suddenly appears in the sky?'}, {'row_idx': 16, 'chunk_type': 'meta', 'title': '0004ngel', 'chunk_text': '0004ngel | Released in 2025-02-26 | Genres: Documentary | Directors: Eli Jean Tahchi | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 16, 'chunk_type': 'plot', 'title': '0004ngel', 'chunk_text': '0004ngel | Plot: To support his mother in Mexico, Angel, a nude dancer, turns the web into his new stage.'}, {'row_idx': 17, 'chunk_type': 'meta', 'title': '0009: The Sharks Make Contact', 'chunk_text': '0009: The Sharks Make Contact | Released in 2020-09-16 | Genres: Animation, Comedy, Music | Directors: Unknown | Cast: Unknown | Production companies: Ènèng Studios | Tags: sequel, anthropomorphic animal, sharks, animation'}, {'row_idx': 17, 'chunk_type': 'plot', 'title': '0009: The Sharks Make Contact', 'chunk_text': "0009: The Sharks Make Contact | Plot: In the sharks' second adventure, a shark's refusal to return a glass of pesto leads to a terrorist crisis."}, {'row_idx': 18, 'chunk_type': 'meta', 'title': "0009: Today's Tomorrow Dies Today", 'chunk_text': "0009: Today's Tomorrow Dies Today | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown"}, {'row_idx': 18, 'chunk_type': 'plot', 'title': "0009: Today's Tomorrow Dies Today", 'chunk_text': "0009: Today's Tomorrow Dies Today | Plot: Agent John Band is tasked with stopping notorious villain Bartholume Jr from launching a stolen nuke"}, {'row_idx': 19, 'chunk_type': 'meta', 'title': "0009: Yesterday's Today Dies Again", 'chunk_text': "0009: Yesterday's Today Dies Again | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown"}, {'row_idx': 19, 'chunk_type': 'plot', 'title': "0009: Yesterday's Today Dies Again", 'chunk_text': "0009: Yesterday's Today Dies Again | Plot: John Band learns that Bartholume Jr. is back and planning to use his evil ray to take over the world"}, {'row_idx': 20, 'chunk_type': 'meta', 'title': '001 Cookie Butter', 'chunk_text': '001 Cookie Butter | Released in 2023-05-04 | Genres: Unknown | Directors: Judebird Dennis | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 20, 'chunk_type': 'plot', 'title': '001 Cookie Butter', 'chunk_text': "001 Cookie Butter | Plot: A raw and introspective film essay that explores the dissonance between the artist's natural self and the violent, industrialized world around them."}, {'row_idx': 21, 'chunk_type': 'meta', 'title': '001 Trolling', 'chunk_text': '001 Trolling | Released in 2017-04-06 | Genres: Comedy | Directors: Gregg Golding | Cast: Phillip Caires, Gregg Golding, Lauren Kane, Anne Luna, Carole Morey | Production companies: Unknown'}, {'row_idx': 21, 'chunk_type': 'plot', 'title': '001 Trolling', 'chunk_text': '001 Trolling | Plot: Two internet anarchists wreak havoc on the world, and each other.'}, {'row_idx': 22, 'chunk_type': 'meta', 'title': '0010: The Sharks Make Contact - Part 2', 'chunk_text': '0010: The Sharks Make Contact - Part 2 | Released in 2020-09-17 | Genres: Animation, Comedy, Science Fiction | Directors: Unknown | Cast: Unknown | Production companies: Ènèng Studios | Tags: moon, shark, anthropomorphic animal, science fiction, animation'}, {'row_idx': 22, 'chunk_type': 'plot', 'title': '0010: The Sharks Make Contact - Part 2', 'chunk_text': '0010: The Sharks Make Contact - Part 2 | Plot: In the aftermath of 0009: The Sharks Make Contact (2019), the surviving sharks have to deal with a destroyed moon, and try to stop Shoogledocking.'}, {'row_idx': 23, 'chunk_type': 'meta', 'title': '001-ing', 'chunk_text': '001-ing | Released in 2006-04-18 | Genres: Unknown | Directors: Lee Ming-Yu | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 23, 'chunk_type': 'plot', 'title': '001-ing', 'chunk_text': '001-ing | Plot: Using hand-processing techniques and super 8mm film material, the film produces unexpected effects on texture. Furthermore, with different speeds of controlling the super 8mm projector, it creates a special rhythm in back-and-forth movements.'}, {'row_idx': 24, 'chunk_type': 'meta', 'title': '002 Heresy', 'chunk_text': '002 Heresy | Released in 2024-06-08 | Genres: Unknown | Directors: Judebird Dennis | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 24, 'chunk_type': 'plot', 'title': '002 Heresy', 'chunk_text': '002 Heresy | Plot: A diary film composed of iPhone footage, internet videos, painted film and original music, documenting the extreme emotional contradictions of living in the American South as a trans woman in 2023.'}, {'row_idx': 25, 'chunk_type': 'meta', 'title': '002 Operation Moon', 'chunk_text': '002 Operation Moon | Released in 1965-11-25 | Genres: Comedy | Directors: Lucio Fulci | Cast: Franco Franchi, Ciccio Ingrassia, Linda Sini, María Silva, Mónica Randall, Elena Sedlak, Emilio Rodríguez, Chiro Bermejo, Ignazio Leone, Franco Moruzzi | Production companies: Ágata Film, IMA Film'}, {'row_idx': 25, 'chunk_type': 'plot', 'title': '002 Operation Moon', 'chunk_text': '002 Operation Moon | Plot: KGB authorities abduct two criminals (Franco and Ciccio) who look exactly like missing spacemen and pretend they are the returning cosmonauts. They launch them in a rocket, so that they can land in public view, leading the populace to believe it was the original space craft that has returned. The two criminals look so much like the astronauts, they even fool the wives of the astronauts. Later however, the original spacecraft returns to Earth undamaged, and the plan goes all to pieces. In the end, Franco and Ciccio stay in Russia and the real astronauts relocate to Italy.'}, {'row_idx': 26, 'chunk_type': 'meta', 'title': '002 - Saints', 'chunk_text': '002 - Saints | Released in 2014-06-10 | Genres: Unknown | Directors: Anonymous | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 26, 'chunk_type': 'plot', 'title': '002 - Saints', 'chunk_text': '002 - Saints | Plot: An ex-priest meets a woman in a lonely parking ramp.  Loosely adapted from the play "100 Saints You Should Know."'}, {'row_idx': 27, 'chunk_type': 'meta', 'title': '0,03 seconds', 'chunk_text': '0,03 seconds | Released in 2017-04-13 | Genres: Documentary | Directors: Suzanne Raes | Cast: Femke Heemskerk, Ranomi Kromowidjojo, Ferry Weertman, Sebastiaan Verschuren, Sharon van Rouwendaal, Marcel Wouda | Production companies: Unknown | Tags: sports, olympic games, swimming'}, {'row_idx': 27, 'chunk_type': 'plot', 'title': '0,03 seconds', 'chunk_text': '0,03 seconds | Plot: A poignant insight into the world of sport, where talent, passion and endurance mean everything, but give no guarantee of success.'}, {'row_idx': 28, 'chunk_type': 'meta', 'title': '006, un principio', 'chunk_text': '006, un principio | Released in 2011-05-06 | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 28, 'chunk_type': 'plot', 'title': '006, un principio', 'chunk_text': '006, un principio | Plot: A man and a woman, who knows they must confront the fear, emerge together from their past and help each other to be reborn.'}, {'row_idx': 29, 'chunk_type': 'meta', 'title': '007 - For Our Eyes Only', 'chunk_text': '007 - For Our Eyes Only | Released in 2020-08-20 | Genres: Documentary | Directors: Miguel Somoza | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 29, 'chunk_type': 'plot', 'title': '007 - For Our Eyes Only', 'chunk_text': '007 - For Our Eyes Only | Plot: In anticipation of the 25th chapter in the iconic James Bond Saga, based on the novels of British writer Ian Fleming, Sabbatical Entertainment presents "For Our Eyes Only" an enthralling documentary that recounts and relives all of 007\'s menacing missions throughout this legendary cinematic franchise, from 1962\'s premiere of "Dr. No", to the highly anticipated "No Time To Die."'}, {'row_idx': 30, 'chunk_type': 'meta', 'title': '007 - Genderbond', 'chunk_text': '007 - Genderbond | Released in 2024-08-26 | Genres: Action | Directors: Evelyn Lanzoni Bolzan | Cast: Marina Gallet | Production companies: Unknown'}, {'row_idx': 30, 'chunk_type': 'plot', 'title': '007 - Genderbond', 'chunk_text': '007 - Genderbond | Plot: In a mysterious proposal focused on introducing the character, Jane Bond enters the dark corridor through the illuminated door. Her silhouette and her eyes are visible with a light source in the corridor. A retelling of a scene from the film "007 - Skyfall".'}, {'row_idx': 31, 'chunk_type': 'meta', 'title': '007 in Egypt', 'chunk_text': '007 in Egypt | Released in 2006-07-17 | Genres: Documentary | Directors: Unknown | Cast: Michael G. Wilson | Production companies: Unknown'}, {'row_idx': 31, 'chunk_type': 'plot', 'title': '007 in Egypt', 'chunk_text': '007 in Egypt | Plot: A look at filming James Bond in Egypt.'}, {'row_idx': 32, 'chunk_type': 'meta', 'title': '007: Licence to Restore', 'chunk_text': '007: Licence to Restore | Released in 2006-07-17 | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 32, 'chunk_type': 'plot', 'title': '007: Licence to Restore', 'chunk_text': '007: Licence to Restore | Plot: A short documentary featurette made for DVD about the film restoration of the original film negatives of the Eon Productions James Bond series. Focuses mainly on the 1960 Bond movies.'}, {'row_idx': 33, 'chunk_type': 'meta', 'title': '007: Out Of Time', 'chunk_text': '007: Out Of Time | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 33, 'chunk_type': 'plot', 'title': '007: Out Of Time', 'chunk_text': '007: Out Of Time | Plot: This low-budget short film follows secret agent 007 as he investigates a mysterious abandoned house in the woods during an eerie winter blizzard.'}, {'row_idx': 34, 'chunk_type': 'meta', 'title': '007: Out Of Time', 'chunk_text': '007: Out Of Time | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 34, 'chunk_type': 'plot', 'title': '007: Out Of Time', 'chunk_text': '007: Out Of Time | Plot: This low-budget short film follows secret agent 007 as he investigates a mysterious house in the woods during an eerie winter blizzard…  Written & shot in 1 day.'}, {'row_idx': 35, 'chunk_type': 'meta', 'title': '007: Out Of Time', 'chunk_text': '007: Out Of Time | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'}, {'row_idx': 35, 'chunk_type': 'plot', 'title': '007: Out Of Time', 'chunk_text': '007: Out Of Time | Plot: This low-budget Jam

In [8]:
idx = 5

meta = data[idx*2]
plot = data[idx*2+1]
print(f"meta: {meta}")
print(f"plot: {plot}")

meta: {'row_idx': 5, 'chunk_type': 'meta', 'title': "0 to 60mph: Britain's Fastest Kids", 'chunk_text': "0 to 60mph: Britain's Fastest Kids | Released in 2016-11-20 | Genres: Documentary | Directors: Unknown | Cast: Unknown | Production companies: Unknown"}
plot: {'row_idx': 5, 'chunk_type': 'plot', 'title': "0 to 60mph: Britain's Fastest Kids", 'chunk_text': "0 to 60mph: Britain's Fastest Kids | Plot: Unveiling Britain’s competitive karting scene and some of Britain’s most promising young drivers, working towards their ultimate goal of reaching Formula One."}

In [5]:
import pandas as pd

df = pd.read_pickle('../../indexes/faiss_metadata.pkl')
df

[{'row_idx': 0,
  'chunk_type': 'meta',
  'title': '0 and 26',
  'chunk_text': '0 and 26 | Released in 2016-12-23 | Genres: Documentary | Directors: Unknown | Cast: Ron Wolf, Steve Spurrier, J.K. McKay, Rich McKay, Pat Toomay, Dewey Selmon, Mark Cotney | Production companies: NFL Films'},
 {'row_idx': 0,
  'chunk_type': 'plot',
  'title': '0 and 26',
  'chunk_text': '0 and 26 | Plot: The Tampa Bay Buccaneers losing their first ever 26 games.'},
 {'row_idx': 1,
  'chunk_type': 'meta',
  'title': '0% Down',
  'chunk_text': '0% Down | Released in 2008-01-01 | Genres: Unknown | Directors: Josephine Meckseper | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 1,
  'chunk_type': 'plot',
  'title': '0% Down',
  'chunk_text': '0% Down | Plot: Meckseper\'s parodic high-octane video 0% Down (2008) engages the politics of consumerism that undeniably extend to the automotive industry. Meckseper edited the most militaristic and aggressive sequences of campaigns produced by various manufacturers—including Ford, Saab, Mazda, Toyota, Mercedes, and Chevrolet—into a six-minute, black-and-white montage. Boyd Rice’s industrial noise anthem “Total War" accompanies the imagery. As a male voice shouts, “Do you want? Yes you want…Total War!” seemingly indestructible cars are glorified in implausible scenarios. A military aircraft morphs into an SUV, a truck drives through swinging metal beams in a rock quarry, and a sedan plays chicken with a fighter jet. While similar types of commercials run daily on American television sets, when grouped together in 0% Down, they appear absurd. - UTexas'},
 {'row_idx': 2,
  'chunk_type': 'meta',
  'title': '0 Feet Away',
  'chunk_text': '0 Feet Away | Released in 2014-12-15 | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 2,
  'chunk_type': 'plot',
  'title': '0 Feet Away',
  'chunk_text': "0 Feet Away | Plot: Looking for a good time, Chase stays home one night searching for a hook-up, using one of the many apps on his phone. What starts off as a flirty conversation with Stealth, ends up getting creepier, until there's not much more than zero feet between them."},
 {'row_idx': 3,
  'chunk_type': 'meta',
  'title': '0 Lux',
  'chunk_text': '0 Lux | Released | Genres: Horror | Directors: Unknown | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 3,
  'chunk_type': 'plot',
  'title': '0 Lux',
  'chunk_text': "0 Lux | Plot: A man clearing out his recently deceased father's house discovers a camcorder that offers a bittersweet glimpse of his father for the last time."},
 {'row_idx': 4,
  'chunk_type': 'meta',
  'title': '#0. sisocisP',
  'chunk_text': '#0. sisocisP | Released in 1992-01-01 | Genres: Unknown | Directors: Antoni Pinent | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 4,
  'chunk_type': 'plot',
  'title': '#0. sisocisP',
  'chunk_text': '#0. sisocisP | Plot: "[An] experiment that aims to highlight the number of shots of a specific scene [from Hitchcock\'s Psycho] by replacing the shot of the image with several of the credit titles from the same film [...] An early work, which would be the first official of Pinent\'s filmography, made when he was only 16 years old, [...] Two years away from Matthias Müller\'s \'found footage\' reference work, \'Home Stories\' (1990), a key piece in the genre." -Center de Cultura Contemporània de Barcelona'},
 {'row_idx': 5,
  'chunk_type': 'meta',
  'title': "0 to 60mph: Britain's Fastest Kids",
  'chunk_text': "0 to 60mph: Britain's Fastest Kids | Released in 2016-11-20 | Genres: Documentary | Directors: Unknown | Cast: Unknown | Production companies: Unknown"},
 {'row_idx': 5,
  'chunk_type': 'plot',
  'title': "0 to 60mph: Britain's Fastest Kids",
  'chunk_text': "0 to 60mph: Britain's Fastest Kids | Plot: Unveiling Britain’s competitive karting scene and some of Britain’s most promising young drivers, working towards their ultimate goal of reaching Formula One."},
 {'row_idx': 6,
  'chunk_type': 'meta',
  'title': '00 Schneider - Im Wendekreis der Eidechse',
  'chunk_text': '00 Schneider - Im Wendekreis der Eidechse | Released in 2013-06-30 | Genres: Comedy | Directors: Helge Schneider | Cast: Helge Schneider, Rocko Schamoni, Sergej Gleithmann, Peter Thoms, Pete York, Tyree Glenn, Rudi Olbrich, Antoinette Clinton | Production companies: Senator Film'},
 {'row_idx': 6,
  'chunk_type': 'plot',
  'title': '00 Schneider - Im Wendekreis der Eidechse',
  'chunk_text': "00 Schneider - Im Wendekreis der Eidechse | Plot: A dangerous gangster called the Lizard escaped from prison. He steals chickens and spits on old ladies. There's only one man who can catch him: the commissioner Roy Schneider!"},
 {'row_idx': 7,
  'chunk_type': 'meta',
  'title': '00 Schneider - Jagd auf Nihil Baxter',
  'chunk_text': '00 Schneider - Jagd auf Nihil Baxter | Released in 1994-12-21 | Genres: Comedy, Crime | Directors: Christoph Schlingensief, Helge Schneider | Cast: Helge Schneider, Helmut Körschgen, Andreas Kunze, Otto Van den Berg, Guenther Kordas, Hotte Reichlich, Charlie Weiss, Tim Janssen, Eva Kurowski, Werner Abrolat | Production companies: Senator Film'},
 {'row_idx': 7,
  'chunk_type': 'plot',
  'title': '00 Schneider - Jagd auf Nihil Baxter',
  'chunk_text': '00 Schneider - Jagd auf Nihil Baxter | Plot: The funny clown Bratislav Metulskie is found dead in circus "Apollo". The retired commissioner 00 Schneider is asked to assume control of the case. Schneider and his aged sidekick Körschgen investigate to find the murderer.'},
 {'row_idx': 8,
  'chunk_type': 'meta',
  'title': '00 Woman - Im Reich der Klofrau',
  'chunk_text': '00 Woman - Im Reich der Klofrau | Released in 2003-01-01 | Genres: Comedy | Directors: Beatrice Manowski | Cast: Beatrice Manowski | Production companies: Unknown'},
 {'row_idx': 8,
  'chunk_type': 'plot',
  'title': '00 Woman - Im Reich der Klofrau',
  'chunk_text': '00 Woman - Im Reich der Klofrau | Plot: The adventures of a toilet cleaner.'},
 {'row_idx': 9,
  'chunk_type': 'meta',
  'title': '0000 Kilometre',
  'chunk_text': '0000 Kilometre | Released in 2024 | Genres: Drama, Romance | Directors: Deniz Enyüksek | Cast: Derya Pınar Ak, Ahmet Haktan Zavlak, Gülin İyigün, Ogün Kaptanoğlu, Cavit Çetin Güner, Can Kızıltuğ, Oya İloğulları, Laçin Ergül, Anıl Özgür, Meltem Akçöl | Production companies: Unknown'},
 {'row_idx': 9,
  'chunk_type': 'plot',
  'title': '0000 Kilometre',
  'chunk_text': "0000 Kilometre | Plot: A phone call to Izmir while she and Ege are living together in France turns their lives upside down. The caller claims to be Izmir's recently deceased mother."},
 {'row_idx': 10,
  'chunk_type': 'meta',
  'title': '00:00 Meia-Noite',
  'chunk_text': '00:00 Meia-Noite | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 10,
  'chunk_type': 'plot',
  'title': '00:00 Meia-Noite',
  'chunk_text': '00:00 Meia-Noite | Plot: An essay on love, friendship, sex, identity and art, led by the gaze of a group of young people who struggle with reaching adulthood.'},
 {'row_idx': 11,
  'chunk_type': 'meta',
  'title': '00:00 Midnight',
  'chunk_text': '00:00 Midnight | Released in 2024 | Genres: Drama, Romance | Directors: Ana Luis Quintão, Filipa Pereira Pinto | Cast: Shanice Prentis, Marta Fatal, Will Costa, Eloy Gomes, Catarina Campos, Inês Meira | Production companies: Unknown'},
 {'row_idx': 11,
  'chunk_type': 'plot',
  'title': '00:00 Midnight',
  'chunk_text': '00:00 Midnight | Plot: An essay on love, friendship, sex, identity and art, led by the gaze of a group of young people who struggle with reaching adulthood.'},
 {'row_idx': 12,
  'chunk_type': 'meta',
  'title': '0000: A Shark Odyssey',
  'chunk_text': '0000: A Shark Odyssey | Released in 2020-09-16 | Genres: Animation, Comedy, Music, Science Fiction | Directors: Unknown | Cast: Unknown | Production companies: Ènèng Studios'},
 {'row_idx': 12,
  'chunk_type': 'plot',
  'title': '0000: A Shark Odyssey',
  'chunk_text': '0000: A Shark Odyssey | Plot: In the year 0000, the world is inhabited by sharks who speak the Sharkish language. But one day everything seems to be coming to an end. Unknown forces want to manipulate these sharks using anagrams.'},
 {'row_idx': 13,
  'chunk_type': 'meta',
  'title': '00:00: Urban Strange Story',
  'chunk_text': '00:00: Urban Strange Story | In Production | Genres: Thriller, Mystery | Directors: Khoa Nguyễn, Nguyễn Đức Nhật Thanh | Cast: Oanh Kiều, Lý Hồng Ân, Nhung Gumiho, Thư Nguyễn, Nguyễn Anh Tú, Bảo Trung | Production companies: nColors Production | Tags: urban life, stranger, chuyện kỳ dị'},
 {'row_idx': 13,
  'chunk_type': 'plot',
  'title': '00:00: Urban Strange Story',
  'chunk_text': '00:00: Urban Strange Story | Plot: The collection of urban strange stories'},
 {'row_idx': 14,
  'chunk_type': 'meta',
  'title': '00007.mov',
  'chunk_text': '00007.mov | Released in 2023-09-18 | Genres: Comedy | Directors: Unknown | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 14,
  'chunk_type': 'plot',
  'title': '00007.mov',
  'chunk_text': '00007.mov | Plot: A group of film students set up equipment to shoot a short film for a 72 hour film challenge.'},
 {'row_idx': 15,
  'chunk_type': 'meta',
  'title': '0000E8',
  'chunk_text': '0000E8 | Released in 2020-09-05 | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 15,
  'chunk_type': 'plot',
  'title': '0000E8',
  'chunk_text': '0000E8 | Plot: What are you going to do when a giant blue star-like object suddenly appears in the sky?'},
 {'row_idx': 16,
  'chunk_type': 'meta',
  'title': '0004ngel',
  'chunk_text': '0004ngel | Released in 2025-02-26 | Genres: Documentary | Directors: Eli Jean Tahchi | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 16,
  'chunk_type': 'plot',
  'title': '0004ngel',
  'chunk_text': '0004ngel | Plot: To support his mother in Mexico, Angel, a nude dancer, turns the web into his new stage.'},
 {'row_idx': 17,
  'chunk_type': 'meta',
  'title': '0009: The Sharks Make Contact',
  'chunk_text': '0009: The Sharks Make Contact | Released in 2020-09-16 | Genres: Animation, Comedy, Music | Directors: Unknown | Cast: Unknown | Production companies: Ènèng Studios | Tags: sequel, anthropomorphic animal, sharks, animation'},
 {'row_idx': 17,
  'chunk_type': 'plot',
  'title': '0009: The Sharks Make Contact',
  'chunk_text': "0009: The Sharks Make Contact | Plot: In the sharks' second adventure, a shark's refusal to return a glass of pesto leads to a terrorist crisis."},
 {'row_idx': 18,
  'chunk_type': 'meta',
  'title': "0009: Today's Tomorrow Dies Today",
  'chunk_text': "0009: Today's Tomorrow Dies Today | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown"},
 {'row_idx': 18,
  'chunk_type': 'plot',
  'title': "0009: Today's Tomorrow Dies Today",
  'chunk_text': "0009: Today's Tomorrow Dies Today | Plot: Agent John Band is tasked with stopping notorious villain Bartholume Jr from launching a stolen nuke"},
 {'row_idx': 19,
  'chunk_type': 'meta',
  'title': "0009: Yesterday's Today Dies Again",
  'chunk_text': "0009: Yesterday's Today Dies Again | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown"},
 {'row_idx': 19,
  'chunk_type': 'plot',
  'title': "0009: Yesterday's Today Dies Again",
  'chunk_text': "0009: Yesterday's Today Dies Again | Plot: John Band learns that Bartholume Jr. is back and planning to use his evil ray to take over the world"},
 {'row_idx': 20,
  'chunk_type': 'meta',
  'title': '001 Cookie Butter',
  'chunk_text': '001 Cookie Butter | Released in 2023-05-04 | Genres: Unknown | Directors: Judebird Dennis | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 20,
  'chunk_type': 'plot',
  'title': '001 Cookie Butter',
  'chunk_text': "001 Cookie Butter | Plot: A raw and introspective film essay that explores the dissonance between the artist's natural self and the violent, industrialized world around them."},
 {'row_idx': 21,
  'chunk_type': 'meta',
  'title': '001 Trolling',
  'chunk_text': '001 Trolling | Released in 2017-04-06 | Genres: Comedy | Directors: Gregg Golding | Cast: Phillip Caires, Gregg Golding, Lauren Kane, Anne Luna, Carole Morey | Production companies: Unknown'},
 {'row_idx': 21,
  'chunk_type': 'plot',
  'title': '001 Trolling',
  'chunk_text': '001 Trolling | Plot: Two internet anarchists wreak havoc on the world, and each other.'},
 {'row_idx': 22,
  'chunk_type': 'meta',
  'title': '0010: The Sharks Make Contact - Part 2',
  'chunk_text': '0010: The Sharks Make Contact - Part 2 | Released in 2020-09-17 | Genres: Animation, Comedy, Science Fiction | Directors: Unknown | Cast: Unknown | Production companies: Ènèng Studios | Tags: moon, shark, anthropomorphic animal, science fiction, animation'},
 {'row_idx': 22,
  'chunk_type': 'plot',
  'title': '0010: The Sharks Make Contact - Part 2',
  'chunk_text': '0010: The Sharks Make Contact - Part 2 | Plot: In the aftermath of 0009: The Sharks Make Contact (2019), the surviving sharks have to deal with a destroyed moon, and try to stop Shoogledocking.'},
 {'row_idx': 23,
  'chunk_type': 'meta',
  'title': '001-ing',
  'chunk_text': '001-ing | Released in 2006-04-18 | Genres: Unknown | Directors: Lee Ming-Yu | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 23,
  'chunk_type': 'plot',
  'title': '001-ing',
  'chunk_text': '001-ing | Plot: Using hand-processing techniques and super 8mm film material, the film produces unexpected effects on texture. Furthermore, with different speeds of controlling the super 8mm projector, it creates a special rhythm in back-and-forth movements.'},
 {'row_idx': 24,
  'chunk_type': 'meta',
  'title': '002 Heresy',
  'chunk_text': '002 Heresy | Released in 2024-06-08 | Genres: Unknown | Directors: Judebird Dennis | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 24,
  'chunk_type': 'plot',
  'title': '002 Heresy',
  'chunk_text': '002 Heresy | Plot: A diary film composed of iPhone footage, internet videos, painted film and original music, documenting the extreme emotional contradictions of living in the American South as a trans woman in 2023.'},
 {'row_idx': 25,
  'chunk_type': 'meta',
  'title': '002 Operation Moon',
  'chunk_text': '002 Operation Moon | Released in 1965-11-25 | Genres: Comedy | Directors: Lucio Fulci | Cast: Franco Franchi, Ciccio Ingrassia, Linda Sini, María Silva, Mónica Randall, Elena Sedlak, Emilio Rodríguez, Chiro Bermejo, Ignazio Leone, Franco Moruzzi | Production companies: Ágata Film, IMA Film'},
 {'row_idx': 25,
  'chunk_type': 'plot',
  'title': '002 Operation Moon',
  'chunk_text': '002 Operation Moon | Plot: KGB authorities abduct two criminals (Franco and Ciccio) who look exactly like missing spacemen and pretend they are the returning cosmonauts. They launch them in a rocket, so that they can land in public view, leading the populace to believe it was the original space craft that has returned. The two criminals look so much like the astronauts, they even fool the wives of the astronauts. Later however, the original spacecraft returns to Earth undamaged, and the plan goes all to pieces. In the end, Franco and Ciccio stay in Russia and the real astronauts relocate to Italy.'},
 {'row_idx': 26,
  'chunk_type': 'meta',
  'title': '002 - Saints',
  'chunk_text': '002 - Saints | Released in 2014-06-10 | Genres: Unknown | Directors: Anonymous | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 26,
  'chunk_type': 'plot',
  'title': '002 - Saints',
  'chunk_text': '002 - Saints | Plot: An ex-priest meets a woman in a lonely parking ramp.  Loosely adapted from the play "100 Saints You Should Know."'},
 {'row_idx': 27,
  'chunk_type': 'meta',
  'title': '0,03 seconds',
  'chunk_text': '0,03 seconds | Released in 2017-04-13 | Genres: Documentary | Directors: Suzanne Raes | Cast: Femke Heemskerk, Ranomi Kromowidjojo, Ferry Weertman, Sebastiaan Verschuren, Sharon van Rouwendaal, Marcel Wouda | Production companies: Unknown | Tags: sports, olympic games, swimming'},
 {'row_idx': 27,
  'chunk_type': 'plot',
  'title': '0,03 seconds',
  'chunk_text': '0,03 seconds | Plot: A poignant insight into the world of sport, where talent, passion and endurance mean everything, but give no guarantee of success.'},
 {'row_idx': 28,
  'chunk_type': 'meta',
  'title': '006, un principio',
  'chunk_text': '006, un principio | Released in 2011-05-06 | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 28,
  'chunk_type': 'plot',
  'title': '006, un principio',
  'chunk_text': '006, un principio | Plot: A man and a woman, who knows they must confront the fear, emerge together from their past and help each other to be reborn.'},
 {'row_idx': 29,
  'chunk_type': 'meta',
  'title': '007 - For Our Eyes Only',
  'chunk_text': '007 - For Our Eyes Only | Released in 2020-08-20 | Genres: Documentary | Directors: Miguel Somoza | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 29,
  'chunk_type': 'plot',
  'title': '007 - For Our Eyes Only',
  'chunk_text': '007 - For Our Eyes Only | Plot: In anticipation of the 25th chapter in the iconic James Bond Saga, based on the novels of British writer Ian Fleming, Sabbatical Entertainment presents "For Our Eyes Only" an enthralling documentary that recounts and relives all of 007\'s menacing missions throughout this legendary cinematic franchise, from 1962\'s premiere of "Dr. No", to the highly anticipated "No Time To Die."'},
 {'row_idx': 30,
  'chunk_type': 'meta',
  'title': '007 - Genderbond',
  'chunk_text': '007 - Genderbond | Released in 2024-08-26 | Genres: Action | Directors: Evelyn Lanzoni Bolzan | Cast: Marina Gallet | Production companies: Unknown'},
 {'row_idx': 30,
  'chunk_type': 'plot',
  'title': '007 - Genderbond',
  'chunk_text': '007 - Genderbond | Plot: In a mysterious proposal focused on introducing the character, Jane Bond enters the dark corridor through the illuminated door. Her silhouette and her eyes are visible with a light source in the corridor. A retelling of a scene from the film "007 - Skyfall".'},
 {'row_idx': 31,
  'chunk_type': 'meta',
  'title': '007 in Egypt',
  'chunk_text': '007 in Egypt | Released in 2006-07-17 | Genres: Documentary | Directors: Unknown | Cast: Michael G. Wilson | Production companies: Unknown'},
 {'row_idx': 31,
  'chunk_type': 'plot',
  'title': '007 in Egypt',
  'chunk_text': '007 in Egypt | Plot: A look at filming James Bond in Egypt.'},
 {'row_idx': 32,
  'chunk_type': 'meta',
  'title': '007: Licence to Restore',
  'chunk_text': '007: Licence to Restore | Released in 2006-07-17 | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 32,
  'chunk_type': 'plot',
  'title': '007: Licence to Restore',
  'chunk_text': '007: Licence to Restore | Plot: A short documentary featurette made for DVD about the film restoration of the original film negatives of the Eon Productions James Bond series. Focuses mainly on the 1960 Bond movies.'},
 {'row_idx': 33,
  'chunk_type': 'meta',
  'title': '007: Out Of Time',
  'chunk_text': '007: Out Of Time | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 33,
  'chunk_type': 'plot',
  'title': '007: Out Of Time',
  'chunk_text': '007: Out Of Time | Plot: This low-budget short film follows secret agent 007 as he investigates a mysterious abandoned house in the woods during an eerie winter blizzard.'},
 {'row_idx': 34,
  'chunk_type': 'meta',
  'title': '007: Out Of Time',
  'chunk_text': '007: Out Of Time | Released | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production companies: Unknown'},
 {'row_idx': 34,
  'chunk_type': 'plot',
  'title': '007: Out Of Time',

In [18]:
import h5py


with h5py.File("../../data/prep/test_embeddings.npy", "r") as hf:
    emb_ds = hf["embeddings"]
    print(emb_ds.len())

600